name : nightly_build

on :
  push :
    branches :
      - master
  workflow_dispatch :

jobs :
  build :
    runs-on : ubuntu-latest
    env:
      BUILD: ${{ github.run_number }}
      SHA: ${{ github.sha }}
      WEBHOOK: ${{ secrets.BUILD_DISCORD_WEBHOOK }}

    steps :
      - name : Check out repository
        uses : actions/checkout@v2

      - name : Check out submodules
        uses : snickerbockers/submodules-init@v4

      - name : Set up JDK
        uses : actions/setup-java@v1
        with :
          java-version : 1.8

      - name : Gradle cache
        uses : actions/cache@v2
        with :
          path : |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key : ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys : |
            ${{ runner.os }}-gradle-

      - name : Build all jars
        run : ./gradlew --build-cache buildAll
        env:
          MOD_VERSION_OVERRIDE: ${{ github.run_number }}

      - name : Generate forge mod checksum
        uses : ToxicAven/generate-checksum-file@v1
        with :
          filePath : lambda-${{ github.run_number }}.jar
          saveFile : forgeModSum.txt
          algorithm : SHA256

      - name : Archive forge mod checksum
        uses : actions/upload-artifact@v2
        with :
          name : forgeModSum.txt
          path : forgeModSum.txt

      - name : Archive forge mod
        uses : actions/upload-artifact@v2
        with :
          name : lambda-${{ github.run_number }}
          path : lambda-${{ github.run_number }}.jar

      - name : Publish API to Maven
        run : ./gradlew --build-cache publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name : Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name : Send Discord build message
        if: github.ref == 'refs/heads/master'
        run : |
          COMMITMESSAGE=`git log --pretty=format:'- \`%h\` %s' -5 --reverse` &&
          (curl "$WEBHOOK" -sS -H "Content-Type:application/json" -X POST -d "{\"content\":null,\"embeds\":[{\"title\":\"Build $BUILD\",\"description\":\"**Branch:** $BRANCH_NAME\\n**Changes:**\\n$COMMITMESSAGE\",\"url\":\"https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\",\"color\":1487872,\"fields\":[{\"name\":\"Artifacts:\",\"value\":\"- [lambda-$BUILD.zip](https://nightly.link/$GITHUB_REPOSITORY/workflows/gradle_build.yml/$BRANCH_NAME/lambda-$BUILD.zip)\"}],\"footer\":{\"text\":\"$GITHUB_REPOSITORY\"},\"thumbnail\":{\"url\":\"https://raw.githubusercontent.com/lambda-client/lambda/master/src/main/resources/assets/minecraft/lambda/lambda_map.png\"}}],\"username\":\"Github Actions\",\"avatar_url\":\"https://www.2b2t.com.au/assets/github.jpeg\"}")